import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-ethers";
import "hardhat-deploy";
import dotenv from "dotenv";

dotenv.config();

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.28",
    settings: {
      evmVersion: "london", // required for Besu
    }
  },
  networks: {
    localhost: {
      url: "http://13.73.227.222:8545",
      chainId: 1337,
      gasPrice: 0,
      gas: 0x1ffffffffffffe,
      accounts: ["0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e", "0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897", "0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd", "0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61", "0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd"] //key generated by hardhat 'npx hardat node'
    },
    docker: {
      url: "http://127.0.0.1:8545",
      chainId: 1337,
      gasPrice: 0,
      gas: 0x1ffffffffffffe,
      accounts: ["0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e", "0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897", "0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd", "0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61", "0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd"] //key generated by hardhat 'npx hardat node'
    },
  },
  namedAccounts: {
    deployer: {
      default: 0,
    },
  },
};

export default config;
